//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordGame.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordGame.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на принято.
        /// </summary>
        internal static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приложение закрыто. Проигрывет: .
        /// </summary>
        internal static string ApplicationClosed {
            get {
                return ResourceManager.GetString("ApplicationClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите язык / Choose language:.
        /// </summary>
        internal static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступные команды: /show-words, /score, /total-score.
        /// </summary>
        internal static string Commands {
            get {
                return ResourceManager.GetString("Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Критическая ошибка: {0}.
        /// </summary>
        internal static string CriticalError {
            get {
                return ResourceManager.GetString("CriticalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Слово не может быть пустым!.
        /// </summary>
        internal static string EmptyWordError {
            get {
                return ResourceManager.GetString("EmptyWordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2 - English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите исходное слово (8-30 символов):.
        /// </summary>
        internal static string EnterBaseWord {
            get {
                return ResourceManager.GetString("EnterBaseWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите имя игрока {0}:.
        /// </summary>
        internal static string EnterPlayerName {
            get {
                return ResourceManager.GetString("EnterPlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите слово (30 секунд):.
        /// </summary>
        internal static string EnterWord {
            get {
                return ResourceManager.GetString("EnterWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла ошибка: {0}.
        /// </summary>
        internal static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на История игр:.
        /// </summary>
        internal static string GameHistory {
            get {
                return ResourceManager.GetString("GameHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игра окончена! Нажмите Enter для выхода....
        /// </summary>
        internal static string GameOver {
            get {
                return ResourceManager.GetString("GameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игра начинается! Исходное слово: {0}.
        /// </summary>
        internal static string GameStarts {
            get {
                return ResourceManager.GetString("GameStarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid choice! Please select 1 or 2..
        /// </summary>
        internal static string InvalidChoice {
            get {
                return ResourceManager.GetString("InvalidChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неизвестная команда.
        /// </summary>
        internal static string InvalidCommand {
            get {
                return ResourceManager.GetString("InvalidCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Слово &apos;{0}&apos; содержит недопустимые буквы!.
        /// </summary>
        internal static string InvalidLetters {
            get {
                return ResourceManager.GetString("InvalidLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Слово должно содержать только буквы!.
        /// </summary>
        internal static string LettersOnlyError {
            get {
                return ResourceManager.GetString("LettersOnlyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на проигрывает!.
        /// </summary>
        internal static string Loses {
            get {
                return ResourceManager.GetString("Loses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поражений.
        /// </summary>
        internal static string Losses {
            get {
                return ResourceManager.GetString("Losses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя слишком длинное! Максимум 20 символов..
        /// </summary>
        internal static string NameTooLong {
            get {
                return ResourceManager.GetString("NameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игр еще не было.
        /// </summary>
        internal static string NoGamesPlayed {
            get {
                return ResourceManager.GetString("NoGamesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет статистики для.
        /// </summary>
        internal static string NoStatisticsFor {
            get {
                return ResourceManager.GetString("NoStatisticsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Слова еще не вводились.
        /// </summary>
        internal static string NoWords {
            get {
                return ResourceManager.GetString("NoWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игрок {0} проиграл!.
        /// </summary>
        internal static string PlayerLost {
            get {
                return ResourceManager.GetString("PlayerLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игрок {0} проиграл!.
        /// </summary>
        internal static string PlayerLostInvalid {
            get {
                return ResourceManager.GetString("PlayerLostInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игрок {0} проиграл! Не успел ввести слово..
        /// </summary>
        internal static string PlayerLostTime {
            get {
                return ResourceManager.GetString("PlayerLostTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игрок {0} проиграл!.
        /// </summary>
        internal static string PlayerLostUsed {
            get {
                return ResourceManager.GetString("PlayerLostUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}: {1} {2}, {3} {4}.
        /// </summary>
        internal static string PlayerStatsLine {
            get {
                return ResourceManager.GetString("PlayerStatsLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ход игрока {0} ({1}).
        /// </summary>
        internal static string PlayerTurn {
            get {
                return ResourceManager.GetString("PlayerTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Последние игры:.
        /// </summary>
        internal static string RecentGames {
            get {
                return ResourceManager.GetString("RecentGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на отклонено.
        /// </summary>
        internal static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1 - Русский.
        /// </summary>
        internal static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать статистику игрока.
        /// </summary>
        internal static string score {
            get {
                return ResourceManager.GetString("score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} vs {1}.
        /// </summary>
        internal static string ScoreBetweenPlayers {
            get {
                return ResourceManager.GetString("ScoreBetweenPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать все слова.
        /// </summary>
        internal static string show_words {
            get {
                return ResourceManager.GetString("show_words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все использованные слова.
        /// </summary>
        internal static string ShowWords {
            get {
                return ResourceManager.GetString("ShowWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статистика для.
        /// </summary>
        internal static string StatisticsFor {
            get {
                return ResourceManager.GetString("StatisticsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время вышло!.
        /// </summary>
        internal static string TimeExpired {
            get {
                return ResourceManager.GetString("TimeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать общую статистику.
        /// </summary>
        internal static string total_score {
            get {
                return ResourceManager.GetString("total_score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Всего попыток.
        /// </summary>
        internal static string TotalAttempts {
            get {
                return ResourceManager.GetString("TotalAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Всего игр.
        /// </summary>
        internal static string TotalGames {
            get {
                return ResourceManager.GetString("TotalGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Всего сыграно игр.
        /// </summary>
        internal static string TotalGamesPlayed {
            get {
                return ResourceManager.GetString("TotalGamesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общая статистика.
        /// </summary>
        internal static string TotalStatistics {
            get {
                return ResourceManager.GetString("TotalStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Использованные слова: {0}.
        /// </summary>
        internal static string UsedWords {
            get {
                return ResourceManager.GetString("UsedWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Процент побед.
        /// </summary>
        internal static string WinRate {
            get {
                return ResourceManager.GetString("WinRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Побед.
        /// </summary>
        internal static string Wins {
            get {
                return ResourceManager.GetString("Wins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Слово &apos;{0}&apos; принято!.
        /// </summary>
        internal static string WordAccepted {
            get {
                return ResourceManager.GetString("WordAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Слово должно быть от 8 до 30 символов!.
        /// </summary>
        internal static string WordLengthError {
            get {
                return ResourceManager.GetString("WordLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Слово &apos;{0}&apos; уже использовалось!.
        /// </summary>
        internal static string WordUsed {
            get {
                return ResourceManager.GetString("WordUsed", resourceCulture);
            }
        }
    }
}
